// Generated by https://quicktype.io

export interface User {
    id:        number;
    username:  string;
    email:     string;
    firstName: string;
    lastName:  string;
    gender:    string;
    image:     string;
    token:     string;
}
